# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FontIconsExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FontIconsExample

  target 'FontIconsExampleTests' do
    # Pods for testing
	pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
  end

end
